name: depi_graduation_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.10
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.4.4
  cached_network_image: ^3.4.1
  flutter_image_slideshow: ^0.1.6
  colornames: ^0.2.0
  carousel_slider_plus: ^7.1.0
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.4
  smooth_page_indicator: ^1.2.0+3
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  location: ^8.0.1
  google_maps_flutter: ^2.12.3
  shared_preferences: ^2.5.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_functions: ^6.0.4
  pin_code_fields: ^7.3.0
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"